twitter:
  # Twitter App
  consumer_key: 073M6GabOkS3UJig5i7PTsM5F
  consumer_secret: wb0nS0yk33iHB0hJn2E7QYdHZFa4mEqJyXbltl33n1gTchwjrT
  access_token: 877292047371296768-y3kWLzR01iIQPxOPWczxx3gkJidnzIY
  access_token_secret: kUgUBaWXzndcFnmqKmLKn2t5gNyObSFBPF8LVAVjZu4Db